### ISSUE TITLE
Language Model

### ISSUE THREAD

**Issue by kradonneoh** [shinhyeokoh/rwen#2]
Hey! 

In the paper you mention that you had a relative CMOS increase of 0.22 when using ELECTRA vs BERT as the pretrained language model.

Do you have any audio samples demonstrating text inputs that have noticeable improvement?

**Comment by kradonneoh** [comment]
Bump!

**Comment by shinhyeokoh** [comment]
The datas are in my previous company, and it's difficult to retrieve it now because I have left the company. I would appreciate your understanding.

By the way, according to the policy of my previous company, we have decided to upload only the RWEN-related code, excluding the TTS module (e.g. fastpitch, vits).

It is scheduled to be uploaded within this month, so please wait for it.

Thank you.
